config/routes.rb
Rails.application.routes.draw do
  resources :videos do
    resources :comments
    member do
      put 'like', to: "videos#like"
      put 'unlike', to: "videos#unlike"
    end
  end
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :video
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :videos, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_voter
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    mount_uploader :thumbnail, ThumbnailUploader
    mount_uploader :videofile, VideofileUploader
    is_impressionable
    acts_as_votable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
  	@video = Video.find(params[:video_id]) # finds the video with the associated video_id
  	@comment = @video.comments.create(comment_params) # creates the comment on the video passing in params 
  	@comment.user_id = current_user.id if current_user # assigns logged in user's ID to comment
  	@comment.save!

  	redirect_to video_path(@video)

  end

  def destroy
  	@video = Video.find(params[:video_id])
  	@comment = @video.comments.find(params[:id])
  	@comment.destroy
  	redirect_to video_path(@video)
  end

  private

  def comment_params 
  	params.require(:comment).permit(:name, :response)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    if params[:search]
      @videos = Video.search(params[:search]).order("created_at DESC")
    else
      @videos = Video.all.order('created_at DESC')
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = current_user.videos.build
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @video.liked_by current_user
    respond_to do |format|
      format.html {redirect_back fallback_location: root_path}
    end
  end

  def unlike
    @video.unliked_by current_user
    respond_to do |format|
      format.html {redirect_back fallback_location: root_path}
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :user_id, :thumbnail, :videofile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.email.gsub('spam', 'mdeering'), alt: comment.user.name, gravatar: { size: 48 }) %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong>
          <div><%= comment.response %></div>
        </p>
      </div>
    </div>
    <% if (user_signed_in? && (current_user.id == comment.user_id)) %>
       <%= link_to 'Delete', [comment.video, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@video, @video.comments.build]) do |f| %>
	<%#= f.input :name, :as => :hidden, :input_html => { :value => current_user.name } %>
	<%= f.hidden_field :name, :value => current_user.name %>
	<div class="field">
		<div class="control">
			<%= f.input :response, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>
	
	<%= f.button :submit, 'Leave a reply', class: 'button is-primary' %>
<% end %>

app/views/home/index.html.erb
<section class="hero is-fullheight video">
    <div class="hero-video">
        <video poster="https://i.imgur.com/xFDgQN3.jpg" id="bgvid" playsinline autoplay muted loop>
            <source src="https://app.coverr.co/s3/mp4/Skater-in-the-Park.mp4" type="video/mp4">
        </video>
    </div>
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-1"><font color="white">Share your Universe!</font></h1>
            <%= link_to new_video_path, class:"button is-primary"  do %>
                <span class="icon is-small"><i class="fa fa-upload"></i></span>
                <span>Upload</span>
            <% end %>
            <%= link_to videos_path, class:"button is-success"  do %>
                <span class="icon is-small"><i class="fa fa-angle-up"></i></span>
                <span>Discover</span>
            <% end %>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share video</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
    	<div class="notification is-primary global-notification">
  	  	<p class="notice"><%= notice %></p>
    	</div>
   	<% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title has-text-white">share_video</h1>
        <% end  %>
          <div class="navbar-burger burger" data-target="navbar">
        </div>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-item">
              <%= link_to 'Discover', videos_path, class:"title is-6 has-text-white" %>
            </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
              <p class="control">
                <%= link_to new_video_path, class:"button is-primary"  do %>
                  <span class="icon is-small"><i class="fa fa-upload"></i></span>
                  <span>Upload</span>
                <% end %>
              </p>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class:"button is-info" %>
              </p>
              <p class="control">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
              <% else %>
              <p class="control">
                 <%= link_to "Sign In", new_user_session_path, class:"button is-primary" %>
              </p>
              <p class="control">
                <%= link_to "Sign Up", new_user_registration_path, class:"button is-success"%>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav> 
    <%= yield %>
  </body>
</html>

app/views/videos/_all.html.erb
<section class="section">
  <div class="videos">
    <% @videos.each do |video| %>
      <div class="video-grid-item">
        <div class="video-wrapper">
          
        <%= link_to video, class: "video" do %>
          <%= image_tag(video.thumbnail_url) %>
          <div class="video-data">
            <div class="video-description"><%= truncate(video.description, length: 60) %></div>
            <div class="video-time">
              <%= time_ago_in_words(video.created_at) %>
            </div>
          </div>
          <h3 class="video-title"><%= video.title %></h3>
        <% end %>

        <nav class="level video-analytics">
          <div class="level-left"></div>
          <div class="level-right">
            <div class="level-item views data">
              <%= link_to video do %>
                <span class="icon"><i class="fa fa-eye"></i></span>
                <%= video.impressionist_count %>
              <% end %>
            </div>
            <div class="level-item comments data">
              <%= link_to video do %>
                <span class="icon"><i class="fa fa-comment"></i></span>
                 <%= video.comments.count %>
              <% end %>
            </div>
            <div class="level-item likes">
              <% if user_signed_in? %>
                <% if current_user.liked? video %>
                  <%= link_to unlike_video_path(video), method: :put, class: "unlike_video" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
                <% else %>
                  <%= link_to like_video_path(video), method: :put, class: "like_video" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
                <% end %>
              <% else %>
                  <%= link_to like_video_path(video), method: :put, class: "like_video" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
              <% end %>
            </div>
          </div>
        </nav>
        </div>
        <div class="user-data">
          <div class="user-thumb">
            <%= gravatar_image_tag(video.user.email.gsub('spam', 'mdeering'), alt: video.user.name, gravatar: { size: 20 }); %>
          </div>
          <div class="user-name"><%= video.user.name %></div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/videos/_form.html.erb
<%= simple_form_for @video, html: { multipart: true }  do |f| %>
  <%= f.error_notification %>
    <ul>
    <% @video.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <div class="columns is-centered">
    <div class="column is-half">
    
    <% unless @video.thumbnail.blank? %>
    <%= image_tag (@video.thumbnail.url), id: "previewImage" %>
    <% end %>

    <div class="field">
      <div class="control">
        <div class="file">
          <label class="file-label">
            <%= f.input :videofile, label: "Video", as: :file, input_html: { class: "file-input", type: "file" } %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a video...
              </span>
            </span>
          </label>
        </div>      
      </div>
    </div>

    <div class="field">
      <div class="control">
        <div class="file">
          <label class="file-label">
            <%= f.input :thumbnail, label: "Thumbnail", as: :file, input_html: { class: "file-input", type: "file" } %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a thumbnail...
              </span>
            </span>
          </label>
        </div>      
      </div>
    </div>

    <div class="field">
      <div class="control">
      	<%= f.input :title, label: "Title", input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
    	<div class="control">
      	<%= f.input :description, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="field">
    	<div class="control">
      	<%= f.button :submit,class:"button is-primary" %>
      </div>
    </div>
  </div>
</div>
 
<% end %>

app/views/videos/edit.html.erb
<section class="section">
	<div class="container">
		<h1 class="title has-text-centered">Editing Video</h1>
		<%= render 'form', video: @video  %>
	</div>
</section>

app/views/videos/index.html.erb
<section class="section">
  <div class="videos">
    <% @videos.each do |video| %>
      <div class="video-grid-item">
        <div class="video-wrapper">
          
        <%= link_to video, class: "video" do %>
          <%= image_tag(video.thumbnail_url) %>
          <div class="video-data">
            <div class="video-description"><%= truncate(video.description, length: 60) %></div>
            <div class="video-time">
              <%= time_ago_in_words(video.created_at) %>
            </div>
          </div>
          <h3 class="video-title"><%= video.title %></h3>
        <% end %>

        <nav class="level video-analytics">
          <div class="level-left"></div>
          <div class="level-right">
            <div class="level-item views data">
              <%= link_to video do %>
                <span class="icon"><i class="fa fa-eye"></i></span>
                <%= video.impressionist_count %>
              <% end %>
            </div>
            <div class="level-item comments data">
              <%= link_to video do %>
                <span class="icon"><i class="fa fa-comment"></i></span>
                 <%= video.comments.count %>
              <% end %>
            </div>
            <div class="level-item likes">
              <% if user_signed_in? %>
                <% if current_user.liked? video %>
                  <%= link_to unlike_video_path(video), method: :put, class: "unlike_video" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
                <% else %>
                  <%= link_to like_video_path(video), method: :put, class: "like_video" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
                <% end %>
              <% else %>
                  <%= link_to like_video_path(video), method: :put, class: "like_video" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= video.get_likes.size %></span>
                  <% end %>
              <% end %>
            </div>
          </div>
        </nav>
        </div>
        <div class="user-data">
          <div class="user-thumb">
            <%= gravatar_image_tag(video.user.email.gsub('spam', 'mdeering'), alt: video.user.name, gravatar: { size: 20 }); %>
          </div>
          <div class="user-name"><%= video.user.name %></div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/videos/new.html.erb
<section class="section">
	<div class="container">
		<h1 class="title is-2 has-text-centered">Share your moments with the world</h1>
		<%= render 'form', video: @video %>
	</div>
</section>

app/views/videos/show.html.erb
<div class="section">
	<div class="container">
  <div class="columns">
    <div class="column is-two-thirds">
      <h1 class="title is-3"><%= @video.title %></h1>
      <div class="columns">
        <div class="column is-8">
          <span class="by has-text-grey-light">by</span>
          <div class="user-thumb">
            <%= gravatar_image_tag(@video.user.email.gsub('spam', 'mdeering'), alt: @video.user.name, gravatar: { size: 20 }); %>
          </div>
          <div class="user-name has-text-weight-bold"><%= @video.user.name %> posted <%= time_ago_in_words(@video.created_at) %> ago</div>
          </span></div>
      </div>
      <%= video_tag @video.videofile, :size => "800x600", :controls => true %>
      <% if user_signed_in? && (current_user.id == @video.user_id) %>		
        <div class="buttons has-addons">
          <%= link_to 'Edit', edit_video_path(@video), class: "button is-info" %>
          <%= link_to 'Delete', video_path, class: "button is-danger", method: :delete, data: { confirm: 'Are you sure you want to delete this video?'} %>
        </div>
      <% end %>
      <div class="box">
        <h1 class="title is-5"> Description </h1>
        <article class="media">
          <p><%= @video.description %></p>
        </article>
      </div>
          
      <section class="comments">
        <h2 class="subtitle is-5"><%= pluralize(@video.comments.count, 'Comment') %></h2>
          <%= render @video.comments %>
        <hr />
        <% if user_signed_in? %>
          <div class="comment-form">
            <h3 class="subtitle is-3">Leave a reply</h3>
            <%= render 'comments/form' %>
          </div>
        <% else %>
          <div class="content"><%= link_to 'Sign in', new_user_session_path %> to leave a comment.</div>
        <% end %>
      </section>  
    </div>
    <div class="column">
      <div class="nav panel show-shot-analytics">
				<div class="panel-block views data">
					<span class="icon"><i class="fa fa-eye"></i></span>
					<%= pluralize(@video.impressionist_count, 'View') %>
			  </div>
				<div class="panel-block comments data">
						<span class="icon"><i class="fa fa-comment"></i></span>
						<%= pluralize(@video.comments.count, 'Comment') %>
				</div>
        <div class="panel-block likes data">
          <% if user_signed_in? %>
            <% if current_user.liked? @video %>
              <%= link_to unlike_video_path(@video), method: :put, class: "unlike_video" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(@video.get_likes.size, 'Like') %></span>
              <% end %>
            <% else %>
              <%= link_to like_video_path(@video), method: :put, class: "like_video" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(@video.get_likes.size, 'Like') %></span>
              <% end %>
            <% end %>
          <% end %>
        </div>  
    </div>
  </div>
  </div>
</div>